# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Generate Changelog"

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    tags:
      - '*'

jobs:
  generate-changelog:
    name: "Generate Changelog"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"

      - name: "Changelog Generator"
        uses: "heinrichreimer/github-changelog-generator-action@v2.1.1"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          releaseBranch: master
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          breakingLabel: "**ğŸ’¥Breaking:**"
          breakingLabels: 'BC Break'
          enhancementLabel: "**ğŸ°Enhancements:**"
          bugsLabel: "**ğŸBugs:**"
          deprecatedLabel: "**ğŸ’€Deprecated:**"
          removedLabel: "**ğŸ—‘Removed:**"
          securityLabel: "**ğŸ›¡Security:**"
          addSections: '{"dependencies":{"prefix":"**ğŸ•¸Dependencies:**","labels":["dependencies"]},"maintenance":{"prefix":"**ğŸ§¹Maintenance:**","labels":["maintenance"]},"documentation":{"prefix":"**ğŸ“¦Documentation:**","labels":["documentation"]}}'
          stripGeneratorNotice: true
          author: true
          usernamesAsGithubLogins: true
          httpCache: false
          filterByMilestone: false
          verbose: true
          excludeLabels: 'duplicate,question,invalid,wontfix'
